<a href="https://colab.research.google.com/github/khudson2021/Probability_Statistics/blob/main/Kristie_Hudson_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

In [ ]:
import numpy as np

### Loops

In [ ]:
for i in range(100): # this outputs the values within the range function 
    print(i) # this prints these values out 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
for i in range(5,8): # this out puts the values within the values 5 through 8 but doesnt include 8 bevause python starts counting from 0
    print(i)

5
6
7


In [ ]:
for i in range(3): # this outputs the values within a range of 3 
    print( "Test Number: " , i ) # this prints out the values through 3 including 0 with the words "Test Number"

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [ ]:
def square(x): # this squares the function with x being the variable in the function 
    return x**2 # this represnts 2 being an exponent of the variable x

In [ ]:
square(5) # this squares the number 5 

25

In [ ]:
square(square(2)) #this squares the number 2 twice 

16

In [ ]:
square(square(square(2))) # this squares the number 2 three times


256

In [ ]:
square(123456) # this squares the number inside the parenthesis 

15241383936

In [ ]:
square(square(5)) # this squares 5 two times 

625

In [ ]:
def add_two(x): # this defines the function so it knows to add two to the variable x 
    return x+2 # this executes the function so that 2 is added to whatever the variable x will be 

In [ ]:
add_two(5) # this adds two to the number 5 which has been placed in the x variable slot 

7

In [ ]:
square(add_two(5)) # this squares the number you get after adding 2 to 5 which is 7 squared 

49

### Logical Branching

In [ ]:
choice = "apple" # this provides the code that apple is the the word of choice for this function

In [ ]:
if choice == "apple": # this is the if statement showing that if the choice apple is presented then...

    print("You choose apples.") # this prints out the statement "You choose apples" if the word apples is presented 

else: # this else statments shows that if the word apples is NOT chosen then...
    
    print("You did not choose apples.") # this prints out the statement "YOu did not choose apples" if any other word besides apples is presented 

You choose apples.


In [ ]:
choice = "orange" # this provides the code that "orange " is the word of choice for this function

In [ ]:
if choice == "apple":  # this shows that is apple is presented then it will print "You choose apples"

    print("You choose apples.")

else: # this shows that if apple is NOT presented then it will print "You did not choose apples"
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple" # this reiterates the code that "apple" is the variable for this function

In [ ]:
if choice == "apple":

    print("You choose apples.") # if the choice is apple then it wil output "You choose apples", "Thank you, shop again!", and then the product of the function 2 with an exponent of 123
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange": # this is th code that presents a separate option of choice which is "orange"

    print("You choose oranges.") # this ensures when the option orange is chosen it will print "You choose oranges." and "Thank you, shop again"
    print("Thank you, shop again!")

else: # this code shows that if neither apple or orange is chosen then...
    
    print("You did not choose apples or oranges.") # this will print out "you did not choose apples or oranges" and "thank you shop sgain!" 
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ") # this code gives the option to input your prefered choice and provides and example which is "apple"

Please enter your choice (i.e. apple): bananas


In [ ]:
choice # this outputs the chosen word typed in the box which in this case i chose "banana"

'bananas'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":     # this is another example of the if, then code just with different ouputs depending on the variable chosen. 

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") # In this case it generated that neither apples or oranges were chosen 

You did not choose apples or oranges.


#### Coins

In [ ]:
np.random.random() # this is a random number generator 

0.051749828133930476

In [ ]:
np.random.random() > 0.5 # this tells whetehr the number is true: greater than 0.5 or false: less than 0.5

False

In [ ]:
def flip_coin(): # this defines the variable flip coin with a function to generate
    if np.random.random() > 0.5: # this outputs whether the coin is true or false to se if its less or greater than 0.5
        print("Heads") # if true then heads will be printed 
    else:
        print("Tails") # if false then tails will be printed

In [ ]:
flip_coin() # this executes the function

Tails


### Graphics Output

In [ ]:
from IPython.core.display import display, HTML # this is tools from a library 

In [ ]:
display(HTML('<h1>Hello, world!</h1>')) # this displays the text hello world as a header 

In [ ]:
def coin(): # this defines the coin function
  return np.random.randint(2) # this outputs a random number between 0-2

In [ ]:
coin() # this executes the function and outputs a random coin

0

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) # this displays the image of the heads coin from the internet

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' # this displays the heads coin image
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' # this displays the tails coin image

In [ ]:
def show_img(img): # this defines the function that displays the image
  display(HTML('<img src=' + img + '>')) # this outputs the image for display along with one of the variables: heads or tails

In [ ]:
show_img(heads) # this executes the function and gives the outcome of heads

In [ ]:
show_img(tails) # this executes the function and gives the outcome of tails

In [ ]:
def flip_coin(): # this defines the flip coin function 

    if coin(): #this shows that if the coin is whatever is in the () then outputs heads 
        show_img(heads)
    else: # this shows that if its anything else then output tails 
        show_img(tails)

In [ ]:
flip_coin() # this randomly flips the coin to test out our funtion 

In [ ]:
for i in range(5): # this is a loop that will give us 5 outputs of either heads or tails
    flip_coin()

In [ ]:
#@title Coin Flip 

if coin(): #this shows that if the coin is whatever is in the () then outputs heads

  show_img(heads)

else:  # this shows that if its anything else then output tails

  show_img(tails)

### Cards

In [ ]:
def shuffle(x): # this defines the shuffle function which presents a list and reorganizes the order of items 
    for i in range(len(x)-1,0,-1): # this creates a list with te numbers ranging and looping with th numbers presented in the ()
        j = np.random.randint(0,i+1) # this code genereates random numbers between 0 and variable i plus 1 
        x[i],x[j] = x[j],x[i] # this execute the function with the the variables that were defined 
        # print(j,x) 
    return x # this outputs the variable x 

In [ ]:
a = np.arange(52) # this arranges the number from 0 to 52, however python starts at 0 and will not include 52

In [ ]:
shuffle(a) # this shuffles all the numbers from 0-52 to that they are all in different order

array([38,  9,  0,  6, 47, 10, 37, 43,  1, 32,  7, 22, 25, 13,  5, 40, 44,
       20, 14, 41, 36,  3, 16,  8, 48,  2, 45, 35, 50, 34, 17, 29, 27, 51,
       19, 24, 49, 12, 18,  4, 33, 39, 21, 11, 15, 28, 26, 46, 23, 31, 30,
       42])

In [ ]:
np.random.permutation(52) # this randomizes the shuffling of the number between 0and 52 

array([28, 38, 50, 30, 11, 20, 41, 46, 42, 37, 27, 13, 49, 48, 21, 29,  5,
       14, 40, 45,  3, 23, 34, 18, 47, 25, 51, 10, 44, 16, 43, 12, 26,  7,
       32, 31, 22, 19, 17,  0, 33,  1,  2,  9, 39, 35,  8, 24, 36, 15,  4,
        6])

### Speed Test

In [ ]:
%%timeit
# this measures the execution time of the cell 
shuffle(a) # this code reorganizes the order of the items presented 

203 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%%timeit
np.random.permutation(52) # this code executes a random permutation per loop

3.67 µs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np # this code is stated to make np import and function properly 

In [ ]:
np.random.permutation(52) # this presents a random assortment of the numbers 0-51

array([40, 44, 50, 21,  3, 47, 49, 37, 30, 38, 12,  1, 22, 11, 14, 20,  9,
       26, 13, 29, 19, 28, 46,  8, 17,  5,  2,  4, 48, 10,  0, 36, 33, 43,
       34, 16,  6, 32,  7, 31, 25, 23, 51, 39, 15, 42, 35, 27, 41, 45, 24,
       18])

In [ ]:
cards = np.random.permutation(52) # this states that this random assortment represents a deck of 52 playing cards

In [ ]:
cards # now once you type cards the assortment will appear 

array([ 9, 32,  6,  3, 25,  0, 42,  1, 38, 40, 21, 17,  7, 10, 34, 30,  8,
       48, 22, 18, 50, 20, 19, 33, 15, 13,  5, 44, 47, 43, 46, 31, 45, 27,
       28, 12,  4, 24, 23, 14, 29, 49, 26, 41, 51, 37, 39, 35, 36,  2, 11,
       16])

In [ ]:
cards[0] # when you imput 0 the number from the random assortment in the 0 slot will appear

9

In [ ]:
cards[1] # when you imput 1 the number from the random assortment in the 1 slot will appear

32

In [ ]:
cards[2] # when you imput 2 the number from the random assortment in the 2 slot will appear

6

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
# this image of a card deck is impoted from the internet

In [ ]:
np.arange(52).reshape(4,13) # this outputs the 52 numbers in random order and gives a new shape to the array without changing the data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 # this puts the numbers in array of 4 rows with the numbers in each row from 0-12 consecutively

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 # this groups each separate number into their own row and repeats that number 12 times

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] # this clarifies the name of the suits so that the word suits can represent all these variables 
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] # this established the names and numbers of the cards in the deck

In [ ]:
def card_name(card_number): # this defines the card name and number in the fucntion
    
    suit = card_number//13 # this shows that a suit equals the card number divided by 13
    name = card_number%13 # this shows that the name equas the card number divided by 13 with a remainder

    return names[name] + " of " + suits[suit]  # this executes the function

In [ ]:
card_name(0) # this shows what card resembles the number 0 in the array

'Ace of Clubs'

In [ ]:
card_name(51) # this shows what card resembles the number 51 in the array

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) # this states that this random assortment represents a deck of 52 playing cards

In [ ]:
top_of_deck         = card_name(cards[0]) # this shows that the top of the deck is going to be the card in slot 0. second card will represent card 1 and the last card will represent -1
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck # this shows which name of the card resembles the top, second, and last card

('Ace of Clubs', 'Three of Diamonds', 'Six of Hearts')

In [ ]:
for i in range(5): # this code gives a range of 5 cards from the deck 
    print(card_name(cards[i])) # this outputs the card names

Ace of Clubs
Three of Diamonds
Two of Diamonds
Seven of Hearts
King of Clubs


In [ ]:
for i in range(15): # this code gives a range of 15 cards from the deck
    print(card_name(cards[i]))

Ace of Clubs
Three of Diamonds
Two of Diamonds
Seven of Hearts
King of Clubs
Two of Clubs
Seven of Diamonds
Six of Clubs
Queen of Clubs
Queen of Hearts
Ace of Spades
Jack of Hearts
Ten of Clubs
Seven of Spades
Two of Spades


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
# this helps display the card pictures and their names from the internet 

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" # this uploads a picture of the cards head and tail from the internet 
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l'] # this labels the variables in the suit in abbreviations 
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] # this labels the names and numbers of the cards in each suit 

In [ ]:
i = np.random.randint(4) # this ouputs 4 random cards 
j = np.random.randint(13) # this outputs 13 random cards 

In [ ]:
i,j # now the letters we used to resemble the cards are randomized and outputted 

(1, 11)

In [ ]:
suit[i] # this shows which suit goes with the variabe i

'p'

In [ ]:
card[j] # this shows which card goes with the suit for variable j

'q'

In [ ]:
from IPython.core.display import display, HTML # this code is used to import and display the images of the cards 

In [ ]:
def show_img(img): # this defines that the imae will show up on python 
  display(HTML('<img src=' + img + '>')) # this diplays the image 

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail # this emsures these specific images will show 

In [ ]:
show_img(img) # this actually imports the image for display 

In [ ]:
def card_image(card_number): # this defines the card image and card number for the function 
    
    i = card_number//13 # this shows that a suit equals the card number divided by 13
    j = card_number%13  # this shows that the name equals the card number divided by 13 with a remainder


    return suit[i]+card[j] # this executes the function 

In [ ]:
card_image(3) # this code is used to display the card number that is in place of the number 3 

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail # this adds the variables together

In [ ]:
show_img(img) # this displays the image for the internet 

In [ ]:
for i in range(52): # this displays the range of 52 cards from the internet 
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)